spring.config.import=optional:classpath:env.properties

# Application
spring.application.name=inventoryService
server.port=8082

# Datasource
spring.datasource.url=jdbc:mysql://${MYSQL_INVENTORY_HOST:localhost}:${MYSQL_INVENTORY_PORT:3308}/${MYSQL_INVENTORY_DB:inventalert_inventory}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=${MYSQL_INVENTORY_USER}
spring.datasource.password=${MYSQL_INVENTORY_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
