-- inventory_user is reserved for a future dedicated service account.
-- Both services currently connect as root (see .env), so no extra grants are needed.
-- When you switch to a dedicated user, add CREATE USER + GRANT statements here.
