package com.inventalert.identityService.integration.repository;

import com.inventalert.identityService.model.Company;
import com.inventalert.identityService.model.CompanyStatus;
import com.inventalert.identityService.repository.CompanyRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.dao.DataIntegrityViolationException;
import org.testcontainers.containers.MySQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers
class CompanyRepositoryIT {

    @Container
    @ServiceConnection
    static MySQLContainer<?> mysql = new MySQLContainer<>("mysql:8");

    @Autowired CompanyRepository companyRepository;

    @BeforeEach
    void clean() {
        companyRepository.deleteAll();
    }

    // ── findByAdminEmail ──────────────────────────────────────────────────────

    @Test
    void findByAdminEmail_existingEmail_returnsCompany() {
        companyRepository.save(buildCompany("Acme Corp", "admin@acme.com"));

        Optional<Company> result = companyRepository.findByAdminEmail("admin@acme.com");

        assertThat(result).isPresent();
        assertThat(result.get().getCompanyName()).isEqualTo("Acme Corp");
    }

    @Test
    void findByAdminEmail_unknownEmail_returnsEmpty() {
        Optional<Company> result = companyRepository.findByAdminEmail("nobody@nowhere.com");
        assertThat(result).isEmpty();
    }

    // ── existsByAdminEmail ────────────────────────────────────────────────────

    @Test
    void existsByAdminEmail_existing_returnsTrue() {
        companyRepository.save(buildCompany("Beta Corp", "admin@beta.com"));

        assertThat(companyRepository.existsByAdminEmail("admin@beta.com")).isTrue();
    }

    @Test
    void existsByAdminEmail_missing_returnsFalse() {
        assertThat(companyRepository.existsByAdminEmail("ghost@nowhere.com")).isFalse();
    }

    // ── Default status ────────────────────────────────────────────────────────

    @Test
    void newCompany_defaultStatusIsActive() {
        Company saved = companyRepository.save(buildCompany("Gamma Corp", "admin@gamma.com"));

        assertThat(saved.getStatus()).isEqualTo(CompanyStatus.ACTIVE);
    }

    // ── Status mutation ───────────────────────────────────────────────────────

    @Test
    void suspendAndReactivate_statusChangesCorrectly() {
        Company company = companyRepository.save(buildCompany("Delta Corp", "admin@delta.com"));

        company.setStatus(CompanyStatus.SUSPENDED);
        Company suspended = companyRepository.save(company);
        assertThat(suspended.getStatus()).isEqualTo(CompanyStatus.SUSPENDED);

        suspended.setStatus(CompanyStatus.ACTIVE);
        Company reactivated = companyRepository.save(suspended);
        assertThat(reactivated.getStatus()).isEqualTo(CompanyStatus.ACTIVE);
    }

    // ── Unique adminEmail constraint ──────────────────────────────────────────

    @Test
    void saveCompany_duplicateAdminEmail_throwsDataIntegrityViolation() {
        companyRepository.save(buildCompany("Epsilon Corp", "admin@epsilon.com"));

        assertThatThrownBy(() ->
                companyRepository.saveAndFlush(buildCompany("Epsilon Two", "admin@epsilon.com")))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    // ── ID auto-generation ────────────────────────────────────────────────────

    @Test
    void savedCompany_idIsAutoGenerated() {
        Company saved = companyRepository.save(buildCompany("Zeta Corp", "admin@zeta.com"));

        assertThat(saved.getId()).isNotNull().isNotBlank();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private Company buildCompany(String name, String email) {
        return Company.builder()
                .companyName(name)
                .adminEmail(email)
                .build();
    }
}
